routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'Frontend\SiteController@index')->name('frontend.home');

//Admin Routes
Route::group(['prefix' => 'admin'], function(){

    Route::name('backend.')->group(function () {

        // Dashboard
        Route::get('/', 'Backend\HomeController@index')->name('home');

        // Users
        Route::get('/users/new_password/{token}','Backend\UsersController@new_password' )->name('users.new_password');
        Route::post('/users/new_password/save','Backend\UsersController@new_password_save' )->name('users.new_password.save');
        Route::post('/users/save','Backend\UsersController@update' )->name('users.save');
        Route::get('/users/destroy/{user}', 'Backend\UsersController@destroy')->name('users.delete');
        Route::resource('users', 'Backend\UsersController')->only(['index', 'store', 'update']);

        // Units
        //Route::get('/units/filter', 'Backend\UnitsController@filter')->name('units.filter');
        Route::post('/units/save','Backend\UnitsController@update')->name('units.save');
        Route::get('units', 'Backend\UnitsController@filter')->name('units.filter');

        // Floor Plans
        Route::post('/floor-plans/save','Backend\FloorPlansController@update' )->name('floor-plans.save');
        Route::resource('floor-plans', 'Backend\FloorPlansController')->only(['index']);

        // Specials
        Route::resource('specials', 'Backend\SpecialsController');

    });

});

app/Special.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Special extends Model
{
    protected $fillable = ['specials', 'leasing_terms', 'pet_policy', 'parking_policy', 'show_special'];
}

app/Http/Controllers/Backend/FloorPlansController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Feature;
use App\FloorPlan;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use function PHPSTORM_META\map;

class FloorPlansController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $floor_plans = FloorPlan::all();

        $rent_ranges = FloorPlan::select(DB::raw("CONCAT(rent_range_min,' - ',rent_range_max) AS rent_range"), 'id')->pluck('rent_range', 'id');
        $terms = FloorPlan::select(DB::raw("CONCAT(term_min,' - ',term_max) AS term"), 'id')->pluck('term', 'id');
        $names = $floor_plans->pluck('name', 'id');
        $deposits = $floor_plans->pluck('deposit', 'id');
        $app_fees = $floor_plans->pluck('app_fee', 'id');
        $dog_deposits = $floor_plans->pluck('dog_deposit', 'id');
        $cat_deposits = $floor_plans->pluck('cat_deposit', 'id');
        $pet_rents = $floor_plans->pluck('pet_rent', 'id');
        $plan_intros = $floor_plans->pluck('plan_intro', 'id');
        $features = $floor_plans->pluck('feature', 'id');

        return view('backend.floor_plans.index', compact('floor_plans', 'names', 'rent_ranges',
            'deposits', 'terms', 'app_fees', 'dog_deposits', 'cat_deposits', 'pet_rents', 'plan_intros', 'features'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $rules =  [
            'rent_range.*'          => 'required|string|min:3',
            'deposit.*'             => 'required|integer',
            'term.*'                => 'required|string|min:3',
            'app_fee.*'             =>'required|integer',
            'dog_deposit.*'         =>'required|integer',
            'cat_deposit.*'         =>'required|integer',
            'pet_rent.*'            =>'required|integer',
            'plan_intro.*'          =>'required|string'
        ];

        $this->validate($request, $rules);

        /*foreach($request->rent_range as $range){
            $ranges = explode('-', $range);
            if(count($ranges)!==2 || !ctype_digit(trim($ranges[0])) || !ctype_digit(trim($ranges[1]))){
                $request->session()->flash('message.level', 'danger');
                $request->session()->flash('message.content', 'The rent range must be integers separated by a hyphen (e.g 1000 - 2000).');
                return redirect()->route('backend.floor-plans.index');
            }
        }*/

        foreach($request->term as $term){
            $terms = explode('-', $term);
            if(count($terms)!==2 || !ctype_digit(trim($terms[0])) || !ctype_digit(trim($terms[1]))){
                $request->session()->flash('message.level', 'danger');
                $request->session()->flash('message.content', 'The term must be integers separated by a hyphen (e.g 6 - 12).');
                return redirect()->route('backend.floor-plans.index');
            }
        }

        $ids = $request->id;
       // $rent_ranges = $request->rent_range;
        $deposits = $request->deposit;
        $terms = $request->term;
        $app_fees = $request->app_fee;
        $dog_deposits = $request->dog_deposit;
        $cat_deposits = $request->cat_deposit;
        $pet_rents = $request->pet_rent;
        $plan_intros = $request->plan_intro;
        $features = $request->feature;

        foreach ($ids as $index=>$id){
            $floor_plan = FloorPlan::find($id);

            $floor_plan->update([
               /* 'rent_range_min' => trim(explode('-', $rent_ranges[$index])[0]),
                'rent_range_max' => trim(explode('-', $rent_ranges[$index])[1]),*/
                'deposit' => $deposits[$index],
                'term_min' => trim(explode('-', $terms[$index])[0]),
                'term_max' => trim(explode('-', $terms[$index])[1]),
                'app_fee'  =>  $app_fees[$index],
                'dog_deposit' => $dog_deposits[$index],
                'cat_deposit' => $cat_deposits[$index],
                'pet_rent' => $pet_rents[$index],
                'plan_intro' => $plan_intros[$index],
                'feature' => $features[$index]
            ]);
        }

        if($floor_plan){
            $request->session()->flash('message.level', 'success');
            $request->session()->flash('message.content', 'Floor Plans successfully updated!');
        }else {
            $request->session()->flash('message.level', 'danger');
            $request->session()->flash('message.content', 'There was an error updating floor plans!');
        }

        return redirect()->route('backend.floor-plans.index');
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;
use App\FloorPlan;
use App\Scheme;
use App\Unit;
use App\User;
use App\Http\Controllers\Controller;
use App\View;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $units_by_plan_type = $this->get_units_by_plan_type();

        $units_by_plan_name = $this->get_units_by_plan_name();

        $units_by_rent_range = $this->get_units_by_rent_range();

        $units_by_floor_no = $this->get_units_by_floor_no();

        $units_by_view = $this->get_units_by_view();

        $units_by_scheme = $this->get_units_by_scheme();

        return view('backend.home', compact('units_by_plan_type', 'units_by_rent_range',
            'units_by_plan_name', 'units_by_floor_no', 'units_by_view', 'units_by_scheme'));
    }

    public function get_units_by_plan_type():array
    {
        $units_by_plan_type_all = array();
        $units_by_plan_type = FloorPlan::withCount('units')->groupBy('type')->get()->pluck('units_count', 'type');

        $all = FloorPlan::withCount('units')->get()->sum('units_count');

        $units_by_plan_type = $units_by_plan_type->toArray();

        $arr = [];
        foreach ($units_by_plan_type as $key=>$type){
            $arr[] = array($key, $type);
        }

        $units_by_plan_type = $arr;

        $units_by_plan_type_all[] = array('Plan Type', 'All Plan Type');
        $units_by_plan_type_all[] = array('All', $all);

        $units_by_plan_type = array_merge($units_by_plan_type_all, $units_by_plan_type);

         return $units_by_plan_type;
    }

    public function get_units_by_rent_range():array
    {
        $rent_min = round(FloorPlan::min('rent_range_min'), -3);
        $rent_max = round(FloorPlan::max('rent_range_min'), -3);
        $units_by_rent_range = array();
        $units_by_rent_range[] = array('Rent Range', 'All Rent Range');
        $units_by_rent_range[] = array('All', Unit::where('rent', '>', 0)->count());
        for($i=$rent_min; $i<=$rent_max; $i+=500){
            $units_count = FloorPlan::whereHas('units', function($query) use($i){
                $query->where([['rent', '>=', $i], ['rent', '<', $i+500]]);
            })->count();
            $units_by_rent_range[] = array('<'.($i+500), $units_count);
        }
        return $units_by_rent_range;
    }

    public function get_units_by_plan_name():array
    {
        $units_by_plan_name = FloorPlan::withCount('units')->get()->pluck('units_count', 'name');

        $units_by_plan_name = $units_by_plan_name->toArray();

        $arr = [];
        foreach ($units_by_plan_name as $key=>$name){
            $arr[] = array($key, $name);
        }

        $units_by_plan_name = $arr;

        $units_by_plan_name_all[] = array('Plan Name', 'All Plan Name');

        $units_by_plan_name= array_merge($units_by_plan_name_all, $units_by_plan_name);

        return $units_by_plan_name;
    }

    public function get_units_by_floor_no():array
    {
        $units_by_floor_no = array();
        $units_by_floor_no[] = array('Floor No', 'All Floor No');
        for($i=3; $i<=7; $i++){
            $units_count = Unit::where('floor_no', $i)->count();
            $units_by_floor_no[] = array($i.'', $units_count);
        }
        return $units_by_floor_no;
    }

    public function get_units_by_view()
    {
        $units_by_view = View::withCount('units')->get()->pluck('units_count', 'name')->toArray();

        $arr = array();
        $arr[] = array('View', 'All View');
        foreach ($units_by_view as $key=>$count){
            $arr[] = array($key, $count);
        }
        $units_by_view = $arr;

        return $units_by_view;
    }

    public function get_units_by_scheme()
    {
        $units_by_scheme = Scheme::withCount('units')->get()->pluck('units_count', 'name')->toArray();

        $arr = array();
        $arr[] = array('Scheme', 'All Scheme');
        foreach ($units_by_scheme as $key=>$count){
            $arr[] = array($key, $count);
        }
        $units_by_scheme = $arr;

        return $units_by_scheme;
    }
}

app/Http/Controllers/Backend/SpecialsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Special;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SpecialsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $specials = Special::find(1);

        return view('backend.specials.index', compact('specials'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Special $special)
    {
        $special->specials = $request->specials;
        $special->leasing_terms = $request->leasing_terms;
        $special->pet_policy = $request->pet_policy;
        $special->parking_policy = $request->parking_policy;
        $special->show_specials = isset($request->show_specials)? 1 : 0;

        if($special->save()){
            $request->session()->flash('message.level', 'success');
            $request->session()->flash('message.content', 'Specials was successfully updated!');
        }else {
            $request->session()->flash('message.level', 'danger');
            $request->session()->flash('message.content', 'There was an error updating specials!');
        }

        return redirect()->route('backend.specials.index');
    }
}

resources/views/backend/specials/index.blade.php
@extends('layouts.backend.master')
@section('pagetitle', 'Leasing & Policies')
@section('css')
    <style>
        .modal-dialog {
            max-width: 665px;
        }


    </style>
@endsection
@section('content')


    <!-- Page Content Starts -->
    <form method="POST" action="{{route('backend.specials.update', ['special'=>1])}}" class="form-horizontal">
        {{ method_field('PUT')}}
        @csrf
    <div class="container lease">
        <div class="row">
            <div class="col-md-2 offset-md-10 savebutton">
                <input class="btn vbtn" type="submit" value="SAVE">
            </div>

                <div class="col-md-6 text">
                    <div class="box">
                        <h5 class="vtitle">SPECIALS<span class="pull-right">Show Specials <input name="show_specials" type="checkbox" {{($specials->show_specials===1)? 'checked' : ''}}></span></h5>
                        <div class="tbox">
                            <textarea name="specials" id="specials">{{$specials->specials}}</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 text">
                    <div class="box">
                        <h5 class="vtitle">LEASING TERMS</h5>
                        <div class="tbox">
                            <textarea name="leasing_terms" id="leasing">{{$specials->leasing_terms}}</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 text">
                    <div class="box">
                        <h5 class="vtitle">PET POLICY</h5>
                        <div class="tbox">
                            <textarea name="pet_policy" id="pet">{{$specials->pet_policy}}</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 text">
                    <div class="box">
                        <h5 class="vtitle">PARKING POLICY</h5>
                        <div class="tbox">
                            <textarea name="parking_policy" id="parking">{{$specials->parking_policy}}</textarea>
                        </div>
                    </div>
                </div>

            <div class="col-md-12 info">
                <p>To create or edit the leasing special which appears on the website just type the special below, formate the text and select the save button.  Check the Show Specials box.  Proof special on the website.</p>
            </div>
        </div>
    </div>
    </form>

@endsection
@section('js')
    <script>

        var isSaved = false;

        let changes = 0;

        $(document).ready(function(){
            CKEDITOR.replace( 'specials');
            CKEDITOR.replace( 'leasing' );
            CKEDITOR.replace( 'pet' );
            CKEDITOR.replace( 'parking' );

            CKEDITOR.instances.specials.on('change', function(){changes++;});
            CKEDITOR.instances.leasing.on('change', function(){changes++;});
            CKEDITOR.instances.pet.on('change', function(){changes++;});
            CKEDITOR.instances.parking.on('change', function(){changes++;});

            $('.vbtn').click(()=>{
                isSaved = true;
            })
        });

        window.onbeforeunload = confirmExit;
        function confirmExit()
        {
            if(isSaved){
                return undefined;
            }
            if(changes>0){
                return "You have attempted to leave this page.  If you have made any changes to the fields without clicking the Save button, your changes will be lost.  Are you sure you want to exit this page?";
            }
        }

    </script>
@endsection